repository: filipradenovic/filipradenovic.github.io

layout: sidebar # sidebar | stacked
style: dark # light | dark

plugins:
  # GitHub Pages plugins
  - jekyll-octicons
  - jekyll-github-metadata
  - jekyll-coffeescript
  - jekyll-commonmark-ghpages
  - jekyll-gist
  - jekyll-paginate
  - jekyll-relative-links
  - jekyll-optional-front-matter
  - jekyll-readme-index
  - jekyll-default-layout
  - jekyll-titles-from-headings
  - jemoji

  # Other plugins
  - jekyll-get-json

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

updates:
  limit: 10
  news:
    - date: '2020-07-01'
      content: 'Query expansion learning paper accepted to ECCV 2020.'
    - date: '2020-06-01'
      content: 'Received Outstanding Reviewer award at the CVPR 2020.'
    - date: '2020-05-01'
      content: Received Antonin Svoboda award for the Best PhD Thesis in 2019 from Czech Society for Cybernetics and Informatics.
    - date: '2019-09-01'
      content: 'Started Research Scientist position at <a class="text-white text-underline" href="https://ai.facebook.com/">Facebook AI</a> in Menlo Park.'
    - date: '2019-09-01'
      content: 'Received Dean''s award for Prestigious PhD Thesis from the Faculty of Electrical Engineering, CTU in Prague.'
    - date: '2019-08-01'
      content: 'Defended <a class="text-white text-underline" href="http://cmp.felk.cvut.cz/publications/Radenovic-TR-2019-01.pdf">PhD Thesis</a> at the Czech Technical University in Prague.'
    - date: '2019-07-01'
      content: 'Targeted mismatch adversarial attack <a class="text-white text-underline" href="http://cmp.felk.cvut.cz/publications/Tolias-ICCV19.pdf">paper</a> accepted to ICCV. <a class="text-white text-underline" href="https://github.com/gtolias/tma">Code</a> available.'
    - date: '2019-06-01'
      content: 'Received Outstanding Reviewer award at the CVPR 2019.'
    - date: '2019-06-01'
      content: 'Our team was ranked 9th / 11th in the Google Landmark <a class="text-white text-underline" href="https://www.kaggle.com/c/landmark-retrieval-2019">Retrieval</a> / <a class="text-white text-underline" href="https://www.kaggle.com/c/landmark-recognition-2019">Recognition</a> 2019 Challenges.'
    # - date: '2018-10-01'
    #   content: '<a class="text-white text-underline" href="http://cmp.felk.cvut.cz/cnnimageretrieval/">Code and data</a> released for our ECCV 2018 <a class="text-white text-underline" href="publications/Radenovic-ECCV18.pdf">paper</a> on deep shape matching.'
    - date: '2018-07-01'
      content: 'Two papers accepted to ECCV 2018: <a class="text-white text-underline" href="publications/Radenovic-ECCV18.pdf">Deep Shape Matching</a> and <a class="text-white text-underline" href="publications/Mishkin-ECCV18.pdf">Learning Affine Regions</a>.'
    - date: '2018-06-01'
      content: 'Our team was ranked 3rd / 6th in the Google Landmark <a class="text-white text-underline" href="https://www.kaggle.com/c/landmark-recognition-challenge">Recognition</a> / <a class="text-white text-underline" href="https://www.kaggle.com/c/landmark-retrieval-challenge">Retrieval</a> Challenges.'
    # - date: '2018-06-01'
    #   content: 'Started research internship at <a class="text-white text-underline" href="https://ai.facebook.com/">Facebook AI</a> in Menlo Park.'
    - date: '2018-04-01'
      content: 'Large-scale image retrieval benchmarking <a class="text-white text-underline" href="http://cmp.felk.cvut.cz/publications/Radenovic-CVPR18.pdf">paper</a> accepted to CVPR as poster. <a class="text-white text-underline" href="http://cmp.felk.cvut.cz/revisitop/">Code and data</a> available.'

publications:
  - year: 2019
    pubs:
      - r19
      - trc19
      - rtc19
  - year: 2018
    pubs:
      - rtc18
      - rit+18
      - mrm18
  - year: 2017
    pubs:
      - mmrm17
  - year: 2016
    pubs:
      - rtc16
      - rsj+16
  - year: 2015
    pubs:
      - rjc15
      - srcf15
      - shr+15
      - cvh+15
  - year: 2014
    pubs:
      - mrcm14
  - year: 2013
    pubs:
      - spr13
      - prs13

projects:
  sort_by: stars # pushed | stars
  limit: 10
  exclude:
    archived: false
    forks: true
    projects:
      - filipradenovic.github.io
  external: # static repo jsons in _data/projects.yml
    projects:
      - tma

# Repositories not owned by me
jekyll_get_json:
  - data: gtolias/tma
    json: 'https://api.github.com/repos/gtolias/tma'

social_media:
  googlescholar: LV6XQ00AAAAJ
  github: filipradenovic

social_media_short:
  researchgate: Filip_Radenovic
  linkedin: filipradenovic
  facebook: filipradenovic.io
  instagram: filip_radenovic

# topics:
#   - name: CSS
#     web_url: https://github.com/topics/css
#     image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/css/css.png

#   - name: Web design

#   - name: Sass
#     web_url: https://github.com/topics/sass
#     image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/sass/sass.png
